version: '3.8'

services:
  checkout-service:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./checkout-service:/app
    command: >
      bash -c "pip install -q -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 8001"
    ports:
      - "8001:8001"
    environment:
      - DAA_LOGS_URL=http://host.docker.internal:8000/logs/
      - PAYMENT_SERVICE_URL=http://payment-service:8002/pay
      - REDIS_HOST=redis-cache
      - REDIS_PORT=6379
    extra_hosts:
      - "host.docker.internal:host-gateway"

  payment-service:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./payment-service:/app
    command: >
      bash -c "pip install -q fastapi uvicorn pydantic && uvicorn app:app --host 0.0.0.0 --port 8002"
    ports:
      - "8002:8002"

  redis-cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
